package model;
// Generated Aug 2, 2017 11:44:35 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AuditUsers generated by hbm2java
 */
public class AuditUsers  implements java.io.Serializable {


     private Integer id;
     private String action;
     private String userName;
     private String createdBy;
     private Date createdDate;

    public AuditUsers() {
    }

	
    public AuditUsers(String userName) {
        this.userName = userName;
    }
    public AuditUsers(String action, String userName, String createdBy, Date createdDate) {
       this.action = action;
       this.userName = userName;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getAction() {
        return this.action;
    }
    
    public void setAction(String action) {
        this.action = action;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }




}


