package model;
// Generated Aug 6, 2017 11:25:33 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AuditUserRolesObjects generated by hbm2java
 */
public class AuditUserRolesObjects  implements java.io.Serializable {


     private Integer id;
     private String action;
     private String userName;
     private Integer roleId;
     private Integer objectId;
     private String createdBy;
     private Date createdDate;

    public AuditUserRolesObjects() {
    }

    public AuditUserRolesObjects(String action, String userName, Integer roleId, Integer objectId, String createdBy, Date createdDate) {
       this.action = action;
       this.userName = userName;
       this.roleId = roleId;
       this.objectId = objectId;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getAction() {
        return this.action;
    }
    
    public void setAction(String action) {
        this.action = action;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public Integer getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
    public Integer getObjectId() {
        return this.objectId;
    }
    
    public void setObjectId(Integer objectId) {
        this.objectId = objectId;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }




}


