package model;
// Generated Aug 6, 2017 11:25:33 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AuditRoles generated by hbm2java
 */
public class AuditRoles  implements java.io.Serializable {


     private Integer id;
     private String action;
     private int roleId;
     private String createdBy;
     private Date createdDate;

    public AuditRoles() {
    }

	
    public AuditRoles(int roleId) {
        this.roleId = roleId;
    }
    public AuditRoles(String action, int roleId, String createdBy, Date createdDate) {
       this.action = action;
       this.roleId = roleId;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getAction() {
        return this.action;
    }
    
    public void setAction(String action) {
        this.action = action;
    }
    public int getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(int roleId) {
        this.roleId = roleId;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }




}


