package model;
// Generated Aug 6, 2017 11:25:33 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AuditPeople generated by hbm2java
 */
public class AuditPeople  implements java.io.Serializable {


     private Integer id;
     private String action;
     private String peopleEmail;
     private String createdBy;
     private Date createdDate;

    public AuditPeople() {
    }

	
    public AuditPeople(String peopleEmail) {
        this.peopleEmail = peopleEmail;
    }
    public AuditPeople(String action, String peopleEmail, String createdBy, Date createdDate) {
       this.action = action;
       this.peopleEmail = peopleEmail;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getAction() {
        return this.action;
    }
    
    public void setAction(String action) {
        this.action = action;
    }
    public String getPeopleEmail() {
        return this.peopleEmail;
    }
    
    public void setPeopleEmail(String peopleEmail) {
        this.peopleEmail = peopleEmail;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }




}


