package model;
// Generated Aug 2, 2017 11:44:35 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DrHeaders generated by hbm2java
 */
public class DrHeaders  implements java.io.Serializable {


     private Integer drHeaderId;
     private Customers customers;
     private String transactionNum;
     private String drStatus;
     private String driverName;
     private String policeNo;
     private Integer rit;
     private String createdBy;
     private Date createdDate;
     private String updatedBy;
     private Date updatedDate;
     private String enabled;
     private String isDeleted;
     private Set drLineses = new HashSet(0);

    public DrHeaders() {
    }

	
    public DrHeaders(Customers customers, String transactionNum) {
        this.customers = customers;
        this.transactionNum = transactionNum;
    }
    public DrHeaders(Customers customers, String transactionNum, String drStatus, String driverName, String policeNo, Integer rit, String createdBy, Date createdDate, String updatedBy, Date updatedDate, String enabled, String isDeleted, Set drLineses) {
       this.customers = customers;
       this.transactionNum = transactionNum;
       this.drStatus = drStatus;
       this.driverName = driverName;
       this.policeNo = policeNo;
       this.rit = rit;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.updatedBy = updatedBy;
       this.updatedDate = updatedDate;
       this.enabled = enabled;
       this.isDeleted = isDeleted;
       this.drLineses = drLineses;
    }
   
    public Integer getDrHeaderId() {
        return this.drHeaderId;
    }
    
    public void setDrHeaderId(Integer drHeaderId) {
        this.drHeaderId = drHeaderId;
    }
    public Customers getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Customers customers) {
        this.customers = customers;
    }
    public String getTransactionNum() {
        return this.transactionNum;
    }
    
    public void setTransactionNum(String transactionNum) {
        this.transactionNum = transactionNum;
    }
    public String getDrStatus() {
        return this.drStatus;
    }
    
    public void setDrStatus(String drStatus) {
        this.drStatus = drStatus;
    }
    public String getDriverName() {
        return this.driverName;
    }
    
    public void setDriverName(String driverName) {
        this.driverName = driverName;
    }
    public String getPoliceNo() {
        return this.policeNo;
    }
    
    public void setPoliceNo(String policeNo) {
        this.policeNo = policeNo;
    }
    public Integer getRit() {
        return this.rit;
    }
    
    public void setRit(Integer rit) {
        this.rit = rit;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    public String getEnabled() {
        return this.enabled;
    }
    
    public void setEnabled(String enabled) {
        this.enabled = enabled;
    }
    public String getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }
    public Set getDrLineses() {
        return this.drLineses;
    }
    
    public void setDrLineses(Set drLineses) {
        this.drLineses = drLineses;
    }




}


