package model;
// Generated Aug 6, 2017 11:25:33 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DrHeaders generated by hbm2java
 */
public class DrHeaders  implements java.io.Serializable {


     private Integer drHeaderId;
     private Customers customers;
     private String transactionNum;
     private String drStatus;
     private String driverName;
     private String policeNo;
     private Integer rit;
     private Date deliveryDateStart;
     private Date deliveryDateEnd;
     private String kmStart;
     private String kmEnd;
     private String kmTotal;
     private Integer areaId;
     private String createdBy;
     private Date createdDate;
     private String updatedBy;
     private Date updatedDate;
     private String enabled;
     private String isDeleted;
     private Set drLineses = new HashSet(0);

    public DrHeaders() {
    }

	
    public DrHeaders(Customers customers, String transactionNum) {
        this.customers = customers;
        this.transactionNum = transactionNum;
    }
    public DrHeaders(Customers customers, String transactionNum, String drStatus, String driverName, String policeNo, Integer rit, Date deliveryDateStart, Date deliveryDateEnd, String kmStart, String kmEnd, String kmTotal, Integer areaId, String createdBy, Date createdDate, String updatedBy, Date updatedDate, String enabled, String isDeleted, Set drLineses) {
       this.customers = customers;
       this.transactionNum = transactionNum;
       this.drStatus = drStatus;
       this.driverName = driverName;
       this.policeNo = policeNo;
       this.rit = rit;
       this.deliveryDateStart = deliveryDateStart;
       this.deliveryDateEnd = deliveryDateEnd;
       this.kmStart = kmStart;
       this.kmEnd = kmEnd;
       this.kmTotal = kmTotal;
       this.areaId = areaId;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.updatedBy = updatedBy;
       this.updatedDate = updatedDate;
       this.enabled = enabled;
       this.isDeleted = isDeleted;
       this.drLineses = drLineses;
    }
   
    public Integer getDrHeaderId() {
        return this.drHeaderId;
    }
    
    public void setDrHeaderId(Integer drHeaderId) {
        this.drHeaderId = drHeaderId;
    }
    public Customers getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Customers customers) {
        this.customers = customers;
    }
    public String getTransactionNum() {
        return this.transactionNum;
    }
    
    public void setTransactionNum(String transactionNum) {
        this.transactionNum = transactionNum;
    }
    public String getDrStatus() {
        return this.drStatus;
    }
    
    public void setDrStatus(String drStatus) {
        this.drStatus = drStatus;
    }
    public String getDriverName() {
        return this.driverName;
    }
    
    public void setDriverName(String driverName) {
        this.driverName = driverName;
    }
    public String getPoliceNo() {
        return this.policeNo;
    }
    
    public void setPoliceNo(String policeNo) {
        this.policeNo = policeNo;
    }
    public Integer getRit() {
        return this.rit;
    }
    
    public void setRit(Integer rit) {
        this.rit = rit;
    }
    public Date getDeliveryDateStart() {
        return this.deliveryDateStart;
    }
    
    public void setDeliveryDateStart(Date deliveryDateStart) {
        this.deliveryDateStart = deliveryDateStart;
    }
    public Date getDeliveryDateEnd() {
        return this.deliveryDateEnd;
    }
    
    public void setDeliveryDateEnd(Date deliveryDateEnd) {
        this.deliveryDateEnd = deliveryDateEnd;
    }
    public String getKmStart() {
        return this.kmStart;
    }
    
    public void setKmStart(String kmStart) {
        this.kmStart = kmStart;
    }
    public String getKmEnd() {
        return this.kmEnd;
    }
    
    public void setKmEnd(String kmEnd) {
        this.kmEnd = kmEnd;
    }
    public String getKmTotal() {
        return this.kmTotal;
    }
    
    public void setKmTotal(String kmTotal) {
        this.kmTotal = kmTotal;
    }
    public Integer getAreaId() {
        return this.areaId;
    }
    
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    public String getEnabled() {
        return this.enabled;
    }
    
    public void setEnabled(String enabled) {
        this.enabled = enabled;
    }
    public String getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }
    public Set getDrLineses() {
        return this.drLineses;
    }
    
    public void setDrLineses(Set drLineses) {
        this.drLineses = drLineses;
    }




}


