package model;
// Generated Jul 9, 2017 10:35:16 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DrHeaders generated by hbm2java
 */
public class DrHeaders  implements java.io.Serializable {


     private String drHeaderId;
     private Customers customers;
     private Users users;
     private String drStatus;
     private Date createdDate;
     private String updatedBy;
     private Date updatedDate;
     private String enabled;
     private Set drLineses = new HashSet(0);

    public DrHeaders() {
    }

	
    public DrHeaders(String drHeaderId, Customers customers, Users users) {
        this.drHeaderId = drHeaderId;
        this.customers = customers;
        this.users = users;
    }
    public DrHeaders(String drHeaderId, Customers customers, Users users, String drStatus, Date createdDate, String updatedBy, Date updatedDate, String enabled, Set drLineses) {
       this.drHeaderId = drHeaderId;
       this.customers = customers;
       this.users = users;
       this.drStatus = drStatus;
       this.createdDate = createdDate;
       this.updatedBy = updatedBy;
       this.updatedDate = updatedDate;
       this.enabled = enabled;
       this.drLineses = drLineses;
    }
   
    public String getDrHeaderId() {
        return this.drHeaderId;
    }
    
    public void setDrHeaderId(String drHeaderId) {
        this.drHeaderId = drHeaderId;
    }
    public Customers getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Customers customers) {
        this.customers = customers;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getDrStatus() {
        return this.drStatus;
    }
    
    public void setDrStatus(String drStatus) {
        this.drStatus = drStatus;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    public String getEnabled() {
        return this.enabled;
    }
    
    public void setEnabled(String enabled) {
        this.enabled = enabled;
    }
    public Set getDrLineses() {
        return this.drLineses;
    }
    
    public void setDrLineses(Set drLineses) {
        this.drLineses = drLineses;
    }




}


