package model;
// Generated Jul 9, 2017 10:35:16 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * DrLineDest generated by hbm2java
 */
public class DrLineDest  implements java.io.Serializable {


     private Integer drLineDestId;
     private Destinations destinations;
     private DrLines drLines;
     private String createdBy;
     private Date createdDate;
     private String updatedBy;
     private Date updatedDate;

    public DrLineDest() {
    }

	
    public DrLineDest(Destinations destinations, DrLines drLines) {
        this.destinations = destinations;
        this.drLines = drLines;
    }
    public DrLineDest(Destinations destinations, DrLines drLines, String createdBy, Date createdDate, String updatedBy, Date updatedDate) {
       this.destinations = destinations;
       this.drLines = drLines;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.updatedBy = updatedBy;
       this.updatedDate = updatedDate;
    }
   
    public Integer getDrLineDestId() {
        return this.drLineDestId;
    }
    
    public void setDrLineDestId(Integer drLineDestId) {
        this.drLineDestId = drLineDestId;
    }
    public Destinations getDestinations() {
        return this.destinations;
    }
    
    public void setDestinations(Destinations destinations) {
        this.destinations = destinations;
    }
    public DrLines getDrLines() {
        return this.drLines;
    }
    
    public void setDrLines(DrLines drLines) {
        this.drLines = drLines;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }




}


