package model;
// Generated Aug 2, 2017 11:44:35 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * DrLines generated by hbm2java
 */
public class DrLines  implements java.io.Serializable {


     private Integer drLineId;
     private Destinations destinations;
     private DrHeaders drHeaders;
     private String deliveryStatus;
     private Double amount;
     private String createdBy;
     private Date createdDate;
     private String updatedBy;
     private Date updatedDate;
     private String enabled;
     private String isDeleted;

    public DrLines() {
    }

	
    public DrLines(DrHeaders drHeaders) {
        this.drHeaders = drHeaders;
    }
    public DrLines(Destinations destinations, DrHeaders drHeaders, String deliveryStatus, Double amount, String createdBy, Date createdDate, String updatedBy, Date updatedDate, String enabled, String isDeleted) {
       this.destinations = destinations;
       this.drHeaders = drHeaders;
       this.deliveryStatus = deliveryStatus;
       this.amount = amount;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.updatedBy = updatedBy;
       this.updatedDate = updatedDate;
       this.enabled = enabled;
       this.isDeleted = isDeleted;
    }
   
    public Integer getDrLineId() {
        return this.drLineId;
    }
    
    public void setDrLineId(Integer drLineId) {
        this.drLineId = drLineId;
    }
    public Destinations getDestinations() {
        return this.destinations;
    }
    
    public void setDestinations(Destinations destinations) {
        this.destinations = destinations;
    }
    public DrHeaders getDrHeaders() {
        return this.drHeaders;
    }
    
    public void setDrHeaders(DrHeaders drHeaders) {
        this.drHeaders = drHeaders;
    }
    public String getDeliveryStatus() {
        return this.deliveryStatus;
    }
    
    public void setDeliveryStatus(String deliveryStatus) {
        this.deliveryStatus = deliveryStatus;
    }
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    public String getEnabled() {
        return this.enabled;
    }
    
    public void setEnabled(String enabled) {
        this.enabled = enabled;
    }
    public String getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }




}


