package model;
// Generated Jul 9, 2017 10:35:16 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DrLines generated by hbm2java
 */
public class DrLines implements java.io.Serializable {

    private Integer drLineId;
    private DrHeaders drHeaders;
    private String driverName;
    private String policeNo;
    private String createdBy;
    private Date createdDate;
    private String updatedBy;
    private Date updatedDate;
    private Set drLineDests = new HashSet(0);

    public DrLines() {
    }

    public DrLines(DrHeaders drHeaders) {
        this.drHeaders = drHeaders;
    }

    public DrLines(Integer drLineId, DrHeaders drHeaders, String driverName, String policeNo, String createdBy, Date createdDate, String updatedBy, Date updatedDate, Set drLineDests) {
        this.drLineId = drLineId;
        this.drHeaders = drHeaders;
        this.driverName = driverName;
        this.policeNo = policeNo;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.updatedBy = updatedBy;
        this.updatedDate = updatedDate;
        this.drLineDests = drLineDests;
    }

    public Integer getDrLineId() {
        return this.drLineId;
    }

    public void setDrLineId(Integer drLineId) {
        this.drLineId = drLineId;
    }

    public DrHeaders getDrHeaders() {
        return this.drHeaders;
    }

    public void setDrHeaders(DrHeaders drHeaders) {
        this.drHeaders = drHeaders;
    }

    public String getDriverName() {
        return this.driverName;
    }

    public void setDriverName(String driverName) {
        this.driverName = driverName;
    }

    public String getPoliceNo() {
        return this.policeNo;
    }

    public void setPoliceNo(String policeNo) {
        this.policeNo = policeNo;
    }

    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Date getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    public String getUpdatedBy() {
        return this.updatedBy;
    }

    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    public Date getUpdatedDate() {
        return this.updatedDate;
    }

    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    public Set getDrLineDests() {
        return this.drLineDests;
    }

    public void setDrLineDests(Set drLineDests) {
        this.drLineDests = drLineDests;
    }

}
