package model;
// Generated Aug 20, 2017 3:58:45 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MstCustomers generated by hbm2java
 */
public class MstCustomers  implements java.io.Serializable {


     private String custId;
     private String legalName;
     private String shortName;
     private String address;
     private String address2;
     private String city;
     private String province;
     private String country;
     private String contactPerson;
     private String contactNumber;
     private String contactEmail;
     private String createdBy;
     private Date createdTime;
     private String updatedBy;
     private Date updatedTime;
     private Integer modificationNum;
     private String isEnabled;
     private String isDeleted;
     private Set trxBillingses = new HashSet(0);
     private Set trxDeliveryRequestses = new HashSet(0);

    public MstCustomers() {
    }

	
    public MstCustomers(String custId) {
        this.custId = custId;
    }
    public MstCustomers(String custId, String legalName, String shortName, String address, String address2, String city, String province, String country, String contactPerson, String contactNumber, String contactEmail, String createdBy, Date createdTime, String updatedBy, Date updatedTime, Integer modificationNum, String isEnabled, String isDeleted, Set trxBillingses, Set trxDeliveryRequestses) {
       this.custId = custId;
       this.legalName = legalName;
       this.shortName = shortName;
       this.address = address;
       this.address2 = address2;
       this.city = city;
       this.province = province;
       this.country = country;
       this.contactPerson = contactPerson;
       this.contactNumber = contactNumber;
       this.contactEmail = contactEmail;
       this.createdBy = createdBy;
       this.createdTime = createdTime;
       this.updatedBy = updatedBy;
       this.updatedTime = updatedTime;
       this.modificationNum = modificationNum;
       this.isEnabled = isEnabled;
       this.isDeleted = isDeleted;
       this.trxBillingses = trxBillingses;
       this.trxDeliveryRequestses = trxDeliveryRequestses;
    }
   
    public String getCustId() {
        return this.custId;
    }
    
    public void setCustId(String custId) {
        this.custId = custId;
    }
    public String getLegalName() {
        return this.legalName;
    }
    
    public void setLegalName(String legalName) {
        this.legalName = legalName;
    }
    public String getShortName() {
        return this.shortName;
    }
    
    public void setShortName(String shortName) {
        this.shortName = shortName;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getAddress2() {
        return this.address2;
    }
    
    public void setAddress2(String address2) {
        this.address2 = address2;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getProvince() {
        return this.province;
    }
    
    public void setProvince(String province) {
        this.province = province;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getContactPerson() {
        return this.contactPerson;
    }
    
    public void setContactPerson(String contactPerson) {
        this.contactPerson = contactPerson;
    }
    public String getContactNumber() {
        return this.contactNumber;
    }
    
    public void setContactNumber(String contactNumber) {
        this.contactNumber = contactNumber;
    }
    public String getContactEmail() {
        return this.contactEmail;
    }
    
    public void setContactEmail(String contactEmail) {
        this.contactEmail = contactEmail;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedTime() {
        return this.createdTime;
    }
    
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Date getUpdatedTime() {
        return this.updatedTime;
    }
    
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }
    public Integer getModificationNum() {
        return this.modificationNum;
    }
    
    public void setModificationNum(Integer modificationNum) {
        this.modificationNum = modificationNum;
    }
    public String getIsEnabled() {
        return this.isEnabled;
    }
    
    public void setIsEnabled(String isEnabled) {
        this.isEnabled = isEnabled;
    }
    public String getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }
    public Set getTrxBillingses() {
        return this.trxBillingses;
    }
    
    public void setTrxBillingses(Set trxBillingses) {
        this.trxBillingses = trxBillingses;
    }
    public Set getTrxDeliveryRequestses() {
        return this.trxDeliveryRequestses;
    }
    
    public void setTrxDeliveryRequestses(Set trxDeliveryRequestses) {
        this.trxDeliveryRequestses = trxDeliveryRequestses;
    }




}


