package model;
// Generated Aug 20, 2017 3:58:45 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MstDropPoints generated by hbm2java
 */
public class MstDropPoints  implements java.io.Serializable {


     private String podId;
     private MstAreas mstAreas;
     private String podShortname;
     private String podFullname;
     private String is24hrOpened;
     private String contactNum;
     private String contactPerson;
     private String email;
     private String address;
     private String address2;
     private String city;
     private String province;
     private String country;
     private String createdBy;
     private Date createdTime;
     private String updatedBy;
     private Date updatedTime;
     private Integer modificationNum;
     private String isEnabled;
     private String isDeleted;
     private Set trxDeliveryRequestsPodses = new HashSet(0);
     private Set mstP2pdistancesesForToPodId = new HashSet(0);
     private Set mstP2pdistancesesForFromPodId = new HashSet(0);

    public MstDropPoints() {
    }

	
    public MstDropPoints(String podId) {
        this.podId = podId;
    }
    public MstDropPoints(String podId, MstAreas mstAreas, String podShortname, String podFullname, String is24hrOpened, String contactNum, String contactPerson, String email, String address, String address2, String city, String province, String country, String createdBy, Date createdTime, String updatedBy, Date updatedTime, Integer modificationNum, String isEnabled, String isDeleted, Set trxDeliveryRequestsPodses, Set mstP2pdistancesesForToPodId, Set mstP2pdistancesesForFromPodId) {
       this.podId = podId;
       this.mstAreas = mstAreas;
       this.podShortname = podShortname;
       this.podFullname = podFullname;
       this.is24hrOpened = is24hrOpened;
       this.contactNum = contactNum;
       this.contactPerson = contactPerson;
       this.email = email;
       this.address = address;
       this.address2 = address2;
       this.city = city;
       this.province = province;
       this.country = country;
       this.createdBy = createdBy;
       this.createdTime = createdTime;
       this.updatedBy = updatedBy;
       this.updatedTime = updatedTime;
       this.modificationNum = modificationNum;
       this.isEnabled = isEnabled;
       this.isDeleted = isDeleted;
       this.trxDeliveryRequestsPodses = trxDeliveryRequestsPodses;
       this.mstP2pdistancesesForToPodId = mstP2pdistancesesForToPodId;
       this.mstP2pdistancesesForFromPodId = mstP2pdistancesesForFromPodId;
    }
   
    public String getPodId() {
        return this.podId;
    }
    
    public void setPodId(String podId) {
        this.podId = podId;
    }
    public MstAreas getMstAreas() {
        return this.mstAreas;
    }
    
    public void setMstAreas(MstAreas mstAreas) {
        this.mstAreas = mstAreas;
    }
    public String getPodShortname() {
        return this.podShortname;
    }
    
    public void setPodShortname(String podShortname) {
        this.podShortname = podShortname;
    }
    public String getPodFullname() {
        return this.podFullname;
    }
    
    public void setPodFullname(String podFullname) {
        this.podFullname = podFullname;
    }
    public String getIs24hrOpened() {
        return this.is24hrOpened;
    }
    
    public void setIs24hrOpened(String is24hrOpened) {
        this.is24hrOpened = is24hrOpened;
    }
    public String getContactNum() {
        return this.contactNum;
    }
    
    public void setContactNum(String contactNum) {
        this.contactNum = contactNum;
    }
    public String getContactPerson() {
        return this.contactPerson;
    }
    
    public void setContactPerson(String contactPerson) {
        this.contactPerson = contactPerson;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getAddress2() {
        return this.address2;
    }
    
    public void setAddress2(String address2) {
        this.address2 = address2;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getProvince() {
        return this.province;
    }
    
    public void setProvince(String province) {
        this.province = province;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedTime() {
        return this.createdTime;
    }
    
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Date getUpdatedTime() {
        return this.updatedTime;
    }
    
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }
    public Integer getModificationNum() {
        return this.modificationNum;
    }
    
    public void setModificationNum(Integer modificationNum) {
        this.modificationNum = modificationNum;
    }
    public String getIsEnabled() {
        return this.isEnabled;
    }
    
    public void setIsEnabled(String isEnabled) {
        this.isEnabled = isEnabled;
    }
    public String getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }
    public Set getTrxDeliveryRequestsPodses() {
        return this.trxDeliveryRequestsPodses;
    }
    
    public void setTrxDeliveryRequestsPodses(Set trxDeliveryRequestsPodses) {
        this.trxDeliveryRequestsPodses = trxDeliveryRequestsPodses;
    }
    public Set getMstP2pdistancesesForToPodId() {
        return this.mstP2pdistancesesForToPodId;
    }
    
    public void setMstP2pdistancesesForToPodId(Set mstP2pdistancesesForToPodId) {
        this.mstP2pdistancesesForToPodId = mstP2pdistancesesForToPodId;
    }
    public Set getMstP2pdistancesesForFromPodId() {
        return this.mstP2pdistancesesForFromPodId;
    }
    
    public void setMstP2pdistancesesForFromPodId(Set mstP2pdistancesesForFromPodId) {
        this.mstP2pdistancesesForFromPodId = mstP2pdistancesesForFromPodId;
    }




}


