package model;
// Generated Aug 20, 2017 3:58:45 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * MstFleetMaintenance generated by hbm2java
 */
public class MstFleetMaintenance  implements java.io.Serializable {


     private Integer rowId;
     private MstFleet mstFleet;
     private Date serviceDate;
     private int serviceKms;
     private String descriptionOfService;
     private String workshopName;
     private String createdBy;
     private Date createdTime;
     private String updatedBy;
     private Date updatedTime;
     private Integer modificationNum;
     private String isEnabled;
     private String isDeleted;

    public MstFleetMaintenance() {
    }

	
    public MstFleetMaintenance(int serviceKms) {
        this.serviceKms = serviceKms;
    }
    public MstFleetMaintenance(MstFleet mstFleet, Date serviceDate, int serviceKms, String descriptionOfService, String workshopName, String createdBy, Date createdTime, String updatedBy, Date updatedTime, Integer modificationNum, String isEnabled, String isDeleted) {
       this.mstFleet = mstFleet;
       this.serviceDate = serviceDate;
       this.serviceKms = serviceKms;
       this.descriptionOfService = descriptionOfService;
       this.workshopName = workshopName;
       this.createdBy = createdBy;
       this.createdTime = createdTime;
       this.updatedBy = updatedBy;
       this.updatedTime = updatedTime;
       this.modificationNum = modificationNum;
       this.isEnabled = isEnabled;
       this.isDeleted = isDeleted;
    }
   
    public Integer getRowId() {
        return this.rowId;
    }
    
    public void setRowId(Integer rowId) {
        this.rowId = rowId;
    }
    public MstFleet getMstFleet() {
        return this.mstFleet;
    }
    
    public void setMstFleet(MstFleet mstFleet) {
        this.mstFleet = mstFleet;
    }
    public Date getServiceDate() {
        return this.serviceDate;
    }
    
    public void setServiceDate(Date serviceDate) {
        this.serviceDate = serviceDate;
    }
    public int getServiceKms() {
        return this.serviceKms;
    }
    
    public void setServiceKms(int serviceKms) {
        this.serviceKms = serviceKms;
    }
    public String getDescriptionOfService() {
        return this.descriptionOfService;
    }
    
    public void setDescriptionOfService(String descriptionOfService) {
        this.descriptionOfService = descriptionOfService;
    }
    public String getWorkshopName() {
        return this.workshopName;
    }
    
    public void setWorkshopName(String workshopName) {
        this.workshopName = workshopName;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedTime() {
        return this.createdTime;
    }
    
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Date getUpdatedTime() {
        return this.updatedTime;
    }
    
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }
    public Integer getModificationNum() {
        return this.modificationNum;
    }
    
    public void setModificationNum(Integer modificationNum) {
        this.modificationNum = modificationNum;
    }
    public String getIsEnabled() {
        return this.isEnabled;
    }
    
    public void setIsEnabled(String isEnabled) {
        this.isEnabled = isEnabled;
    }
    public String getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }




}


