package model;
// Generated Aug 20, 2017 3:58:45 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * MstFleetInsurance generated by hbm2java
 */
public class MstFleetInsurance  implements java.io.Serializable {


     private Integer rowId;
     private MstFleet mstFleet;
     private String policyNum;
     private Date policyExpiry;
     private String insurerName;
     private String insuredClause;
     private int insuredAmt;
     private int premiumAmt;
     private String createdBy;
     private Date createdTime;
     private String updatedBy;
     private Date updatedTime;
     private Integer modificationNum;
     private String isEnabled;
     private String isDeleted;

    public MstFleetInsurance() {
    }

	
    public MstFleetInsurance(MstFleet mstFleet, int insuredAmt, int premiumAmt) {
        this.mstFleet = mstFleet;
        this.insuredAmt = insuredAmt;
        this.premiumAmt = premiumAmt;
    }
    public MstFleetInsurance(MstFleet mstFleet, String policyNum, Date policyExpiry, String insurerName, String insuredClause, int insuredAmt, int premiumAmt, String createdBy, Date createdTime, String updatedBy, Date updatedTime, Integer modificationNum, String isEnabled, String isDeleted) {
       this.mstFleet = mstFleet;
       this.policyNum = policyNum;
       this.policyExpiry = policyExpiry;
       this.insurerName = insurerName;
       this.insuredClause = insuredClause;
       this.insuredAmt = insuredAmt;
       this.premiumAmt = premiumAmt;
       this.createdBy = createdBy;
       this.createdTime = createdTime;
       this.updatedBy = updatedBy;
       this.updatedTime = updatedTime;
       this.modificationNum = modificationNum;
       this.isEnabled = isEnabled;
       this.isDeleted = isDeleted;
    }
   
    public Integer getRowId() {
        return this.rowId;
    }
    
    public void setRowId(Integer rowId) {
        this.rowId = rowId;
    }
    public MstFleet getMstFleet() {
        return this.mstFleet;
    }
    
    public void setMstFleet(MstFleet mstFleet) {
        this.mstFleet = mstFleet;
    }
    public String getPolicyNum() {
        return this.policyNum;
    }
    
    public void setPolicyNum(String policyNum) {
        this.policyNum = policyNum;
    }
    public Date getPolicyExpiry() {
        return this.policyExpiry;
    }
    
    public void setPolicyExpiry(Date policyExpiry) {
        this.policyExpiry = policyExpiry;
    }
    public String getInsurerName() {
        return this.insurerName;
    }
    
    public void setInsurerName(String insurerName) {
        this.insurerName = insurerName;
    }
    public String getInsuredClause() {
        return this.insuredClause;
    }
    
    public void setInsuredClause(String insuredClause) {
        this.insuredClause = insuredClause;
    }
    public int getInsuredAmt() {
        return this.insuredAmt;
    }
    
    public void setInsuredAmt(int insuredAmt) {
        this.insuredAmt = insuredAmt;
    }
    public int getPremiumAmt() {
        return this.premiumAmt;
    }
    
    public void setPremiumAmt(int premiumAmt) {
        this.premiumAmt = premiumAmt;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedTime() {
        return this.createdTime;
    }
    
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Date getUpdatedTime() {
        return this.updatedTime;
    }
    
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }
    public Integer getModificationNum() {
        return this.modificationNum;
    }
    
    public void setModificationNum(Integer modificationNum) {
        this.modificationNum = modificationNum;
    }
    public String getIsEnabled() {
        return this.isEnabled;
    }
    
    public void setIsEnabled(String isEnabled) {
        this.isEnabled = isEnabled;
    }
    public String getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }




}


