package model;
// Generated Aug 20, 2017 3:58:45 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * MstP2pdistances generated by hbm2java
 */
public class MstP2pdistances  implements java.io.Serializable {


     private MstP2pdistancesId id;
     private MstDropPoints mstDropPointsByToPodId;
     private MstDropPoints mstDropPointsByFromPodId;
     private int p2pdistance;
     private String createdBy;
     private Date createdTime;
     private String updatedBy;
     private Date updatedTime;
     private Integer modificationNum;
     private String isEnabled;
     private String isDeleted;

    public MstP2pdistances() {
    }

	
    public MstP2pdistances(MstP2pdistancesId id, MstDropPoints mstDropPointsByToPodId, MstDropPoints mstDropPointsByFromPodId, int p2pdistance) {
        this.id = id;
        this.mstDropPointsByToPodId = mstDropPointsByToPodId;
        this.mstDropPointsByFromPodId = mstDropPointsByFromPodId;
        this.p2pdistance = p2pdistance;
    }
    public MstP2pdistances(MstP2pdistancesId id, MstDropPoints mstDropPointsByToPodId, MstDropPoints mstDropPointsByFromPodId, int p2pdistance, String createdBy, Date createdTime, String updatedBy, Date updatedTime, Integer modificationNum, String isEnabled, String isDeleted) {
       this.id = id;
       this.mstDropPointsByToPodId = mstDropPointsByToPodId;
       this.mstDropPointsByFromPodId = mstDropPointsByFromPodId;
       this.p2pdistance = p2pdistance;
       this.createdBy = createdBy;
       this.createdTime = createdTime;
       this.updatedBy = updatedBy;
       this.updatedTime = updatedTime;
       this.modificationNum = modificationNum;
       this.isEnabled = isEnabled;
       this.isDeleted = isDeleted;
    }
   
    public MstP2pdistancesId getId() {
        return this.id;
    }
    
    public void setId(MstP2pdistancesId id) {
        this.id = id;
    }
    public MstDropPoints getMstDropPointsByToPodId() {
        return this.mstDropPointsByToPodId;
    }
    
    public void setMstDropPointsByToPodId(MstDropPoints mstDropPointsByToPodId) {
        this.mstDropPointsByToPodId = mstDropPointsByToPodId;
    }
    public MstDropPoints getMstDropPointsByFromPodId() {
        return this.mstDropPointsByFromPodId;
    }
    
    public void setMstDropPointsByFromPodId(MstDropPoints mstDropPointsByFromPodId) {
        this.mstDropPointsByFromPodId = mstDropPointsByFromPodId;
    }
    public int getP2pdistance() {
        return this.p2pdistance;
    }
    
    public void setP2pdistance(int p2pdistance) {
        this.p2pdistance = p2pdistance;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedTime() {
        return this.createdTime;
    }
    
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Date getUpdatedTime() {
        return this.updatedTime;
    }
    
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }
    public Integer getModificationNum() {
        return this.modificationNum;
    }
    
    public void setModificationNum(Integer modificationNum) {
        this.modificationNum = modificationNum;
    }
    public String getIsEnabled() {
        return this.isEnabled;
    }
    
    public void setIsEnabled(String isEnabled) {
        this.isEnabled = isEnabled;
    }
    public String getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }




}


