package model;
// Generated Aug 20, 2017 3:58:45 PM by Hibernate Tools 4.3.1



/**
 * MstP2pdistancesId generated by hbm2java
 */
public class MstP2pdistancesId  implements java.io.Serializable {


     private String fromPodId;
     private String toPodId;

    public MstP2pdistancesId() {
    }

    public MstP2pdistancesId(String fromPodId, String toPodId) {
       this.fromPodId = fromPodId;
       this.toPodId = toPodId;
    }
   
    public String getFromPodId() {
        return this.fromPodId;
    }
    
    public void setFromPodId(String fromPodId) {
        this.fromPodId = fromPodId;
    }
    public String getToPodId() {
        return this.toPodId;
    }
    
    public void setToPodId(String toPodId) {
        this.toPodId = toPodId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MstP2pdistancesId) ) return false;
		 MstP2pdistancesId castOther = ( MstP2pdistancesId ) other; 
         
		 return ( (this.getFromPodId()==castOther.getFromPodId()) || ( this.getFromPodId()!=null && castOther.getFromPodId()!=null && this.getFromPodId().equals(castOther.getFromPodId()) ) )
 && ( (this.getToPodId()==castOther.getToPodId()) || ( this.getToPodId()!=null && castOther.getToPodId()!=null && this.getToPodId().equals(castOther.getToPodId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getFromPodId() == null ? 0 : this.getFromPodId().hashCode() );
         result = 37 * result + ( getToPodId() == null ? 0 : this.getToPodId().hashCode() );
         return result;
   }   


}


