package model;
// Generated Aug 20, 2017 3:58:45 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * MstSequences generated by hbm2java
 */
public class MstSequences  implements java.io.Serializable {


     private String seqId;
     private String format;
     private int nextCounter;
     private int maxCounter;
     private Integer currentYear;
     private String isAutoReset;
     private String createdBy;
     private Date createdTime;
     private String updatedBy;
     private Date updatedTime;
     private Integer modificationNum;
     private String isEnabled;
     private String isDeleted;

    public MstSequences() {
    }

	
    public MstSequences(String seqId, int nextCounter, int maxCounter, String isAutoReset) {
        this.seqId = seqId;
        this.nextCounter = nextCounter;
        this.maxCounter = maxCounter;
        this.isAutoReset = isAutoReset;
    }
    public MstSequences(String seqId, String format, int nextCounter, int maxCounter, Integer currentYear, String isAutoReset, String createdBy, Date createdTime, String updatedBy, Date updatedTime, Integer modificationNum, String isEnabled, String isDeleted) {
       this.seqId = seqId;
       this.format = format;
       this.nextCounter = nextCounter;
       this.maxCounter = maxCounter;
       this.currentYear = currentYear;
       this.isAutoReset = isAutoReset;
       this.createdBy = createdBy;
       this.createdTime = createdTime;
       this.updatedBy = updatedBy;
       this.updatedTime = updatedTime;
       this.modificationNum = modificationNum;
       this.isEnabled = isEnabled;
       this.isDeleted = isDeleted;
    }
   
    public String getSeqId() {
        return this.seqId;
    }
    
    public void setSeqId(String seqId) {
        this.seqId = seqId;
    }
    public String getFormat() {
        return this.format;
    }
    
    public void setFormat(String format) {
        this.format = format;
    }
    public int getNextCounter() {
        return this.nextCounter;
    }
    
    public void setNextCounter(int nextCounter) {
        this.nextCounter = nextCounter;
    }
    public int getMaxCounter() {
        return this.maxCounter;
    }
    
    public void setMaxCounter(int maxCounter) {
        this.maxCounter = maxCounter;
    }
    public Integer getCurrentYear() {
        return this.currentYear;
    }
    
    public void setCurrentYear(Integer currentYear) {
        this.currentYear = currentYear;
    }
    public String getIsAutoReset() {
        return this.isAutoReset;
    }
    
    public void setIsAutoReset(String isAutoReset) {
        this.isAutoReset = isAutoReset;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedTime() {
        return this.createdTime;
    }
    
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Date getUpdatedTime() {
        return this.updatedTime;
    }
    
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }
    public Integer getModificationNum() {
        return this.modificationNum;
    }
    
    public void setModificationNum(Integer modificationNum) {
        this.modificationNum = modificationNum;
    }
    public String getIsEnabled() {
        return this.isEnabled;
    }
    
    public void setIsEnabled(String isEnabled) {
        this.isEnabled = isEnabled;
    }
    public String getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }




}


