package model;
// Generated Aug 20, 2017 3:58:45 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * SysKeywords generated by hbm2java
 */
public class SysKeywords  implements java.io.Serializable {


     private Integer rowId;
     private String keywordId;
     private Integer keyOrder;
     private String keyLabel;
     private String keyValue;
     private String keyDescription;
     private String createdBy;
     private Date createdTime;
     private String updatedBy;
     private Date updatedTime;
     private Integer modificationNum;
     private String isEnabled;
     private String isDeleted;

    public SysKeywords() {
    }

    public SysKeywords(String keywordId, Integer keyOrder, String keyLabel, String keyValue, String keyDescription, String createdBy, Date createdTime, String updatedBy, Date updatedTime, Integer modificationNum, String isEnabled, String isDeleted) {
       this.keywordId = keywordId;
       this.keyOrder = keyOrder;
       this.keyLabel = keyLabel;
       this.keyValue = keyValue;
       this.keyDescription = keyDescription;
       this.createdBy = createdBy;
       this.createdTime = createdTime;
       this.updatedBy = updatedBy;
       this.updatedTime = updatedTime;
       this.modificationNum = modificationNum;
       this.isEnabled = isEnabled;
       this.isDeleted = isDeleted;
    }
   
    public Integer getRowId() {
        return this.rowId;
    }
    
    public void setRowId(Integer rowId) {
        this.rowId = rowId;
    }
    public String getKeywordId() {
        return this.keywordId;
    }
    
    public void setKeywordId(String keywordId) {
        this.keywordId = keywordId;
    }
    public Integer getKeyOrder() {
        return this.keyOrder;
    }
    
    public void setKeyOrder(Integer keyOrder) {
        this.keyOrder = keyOrder;
    }
    public String getKeyLabel() {
        return this.keyLabel;
    }
    
    public void setKeyLabel(String keyLabel) {
        this.keyLabel = keyLabel;
    }
    public String getKeyValue() {
        return this.keyValue;
    }
    
    public void setKeyValue(String keyValue) {
        this.keyValue = keyValue;
    }
    public String getKeyDescription() {
        return this.keyDescription;
    }
    
    public void setKeyDescription(String keyDescription) {
        this.keyDescription = keyDescription;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedTime() {
        return this.createdTime;
    }
    
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Date getUpdatedTime() {
        return this.updatedTime;
    }
    
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }
    public Integer getModificationNum() {
        return this.modificationNum;
    }
    
    public void setModificationNum(Integer modificationNum) {
        this.modificationNum = modificationNum;
    }
    public String getIsEnabled() {
        return this.isEnabled;
    }
    
    public void setIsEnabled(String isEnabled) {
        this.isEnabled = isEnabled;
    }
    public String getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }




}


