package model;
// Generated Aug 20, 2017 3:58:45 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SysRoles generated by hbm2java
 */
public class SysRoles  implements java.io.Serializable {


     private String roleId;
     private String roleDescription;
     private String createdBy;
     private Date createdTime;
     private String updatedBy;
     private Date updatedTime;
     private Integer modificationNum;
     private String isEnabled;
     private String isDeleted;
     private Set sysUsersRoleses = new HashSet(0);
     private Set sysRolesObjectses = new HashSet(0);

    public SysRoles() {
    }

	
    public SysRoles(String roleId) {
        this.roleId = roleId;
    }
    public SysRoles(String roleId, String roleDescription, String createdBy, Date createdTime, String updatedBy, Date updatedTime, Integer modificationNum, String isEnabled, String isDeleted, Set sysUsersRoleses, Set sysRolesObjectses) {
       this.roleId = roleId;
       this.roleDescription = roleDescription;
       this.createdBy = createdBy;
       this.createdTime = createdTime;
       this.updatedBy = updatedBy;
       this.updatedTime = updatedTime;
       this.modificationNum = modificationNum;
       this.isEnabled = isEnabled;
       this.isDeleted = isDeleted;
       this.sysUsersRoleses = sysUsersRoleses;
       this.sysRolesObjectses = sysRolesObjectses;
    }
   
    public String getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }
    public String getRoleDescription() {
        return this.roleDescription;
    }
    
    public void setRoleDescription(String roleDescription) {
        this.roleDescription = roleDescription;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedTime() {
        return this.createdTime;
    }
    
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Date getUpdatedTime() {
        return this.updatedTime;
    }
    
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }
    public Integer getModificationNum() {
        return this.modificationNum;
    }
    
    public void setModificationNum(Integer modificationNum) {
        this.modificationNum = modificationNum;
    }
    public String getIsEnabled() {
        return this.isEnabled;
    }
    
    public void setIsEnabled(String isEnabled) {
        this.isEnabled = isEnabled;
    }
    public String getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }
    public Set getSysUsersRoleses() {
        return this.sysUsersRoleses;
    }
    
    public void setSysUsersRoleses(Set sysUsersRoleses) {
        this.sysUsersRoleses = sysUsersRoleses;
    }
    public Set getSysRolesObjectses() {
        return this.sysRolesObjectses;
    }
    
    public void setSysRolesObjectses(Set sysRolesObjectses) {
        this.sysRolesObjectses = sysRolesObjectses;
    }




}


