package model;
// Generated Aug 20, 2017 3:58:45 PM by Hibernate Tools 4.3.1



/**
 * SysRolesObjectsId generated by hbm2java
 */
public class SysRolesObjectsId  implements java.io.Serializable {


     private String roleId;
     private String objectId;
     private String accessRight;

    public SysRolesObjectsId() {
    }

    public SysRolesObjectsId(String roleId, String objectId, String accessRight) {
       this.roleId = roleId;
       this.objectId = objectId;
       this.accessRight = accessRight;
    }
   
    public String getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }
    public String getObjectId() {
        return this.objectId;
    }
    
    public void setObjectId(String objectId) {
        this.objectId = objectId;
    }
    public String getAccessRight() {
        return this.accessRight;
    }
    
    public void setAccessRight(String accessRight) {
        this.accessRight = accessRight;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SysRolesObjectsId) ) return false;
		 SysRolesObjectsId castOther = ( SysRolesObjectsId ) other; 
         
		 return ( (this.getRoleId()==castOther.getRoleId()) || ( this.getRoleId()!=null && castOther.getRoleId()!=null && this.getRoleId().equals(castOther.getRoleId()) ) )
 && ( (this.getObjectId()==castOther.getObjectId()) || ( this.getObjectId()!=null && castOther.getObjectId()!=null && this.getObjectId().equals(castOther.getObjectId()) ) )
 && ( (this.getAccessRight()==castOther.getAccessRight()) || ( this.getAccessRight()!=null && castOther.getAccessRight()!=null && this.getAccessRight().equals(castOther.getAccessRight()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getRoleId() == null ? 0 : this.getRoleId().hashCode() );
         result = 37 * result + ( getObjectId() == null ? 0 : this.getObjectId().hashCode() );
         result = 37 * result + ( getAccessRight() == null ? 0 : this.getAccessRight().hashCode() );
         return result;
   }   


}


