package model;
// Generated Aug 20, 2017 3:58:45 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * SysRolesObjects generated by hbm2java
 */
public class SysRolesObjects  implements java.io.Serializable {


     private SysRolesObjectsId id;
     private SysObjects sysObjects;
     private SysRoles sysRoles;
     private String createdBy;
     private Date createdTime;
     private String updatedBy;
     private Date updatedTime;
     private Integer modificationNum;
     private String isEnabled;
     private String isDeleted;

    public SysRolesObjects() {
    }

	
    public SysRolesObjects(SysRolesObjectsId id, SysObjects sysObjects, SysRoles sysRoles) {
        this.id = id;
        this.sysObjects = sysObjects;
        this.sysRoles = sysRoles;
    }
    public SysRolesObjects(SysRolesObjectsId id, SysObjects sysObjects, SysRoles sysRoles, String createdBy, Date createdTime, String updatedBy, Date updatedTime, Integer modificationNum, String isEnabled, String isDeleted) {
       this.id = id;
       this.sysObjects = sysObjects;
       this.sysRoles = sysRoles;
       this.createdBy = createdBy;
       this.createdTime = createdTime;
       this.updatedBy = updatedBy;
       this.updatedTime = updatedTime;
       this.modificationNum = modificationNum;
       this.isEnabled = isEnabled;
       this.isDeleted = isDeleted;
    }
   
    public SysRolesObjectsId getId() {
        return this.id;
    }
    
    public void setId(SysRolesObjectsId id) {
        this.id = id;
    }
    public SysObjects getSysObjects() {
        return this.sysObjects;
    }
    
    public void setSysObjects(SysObjects sysObjects) {
        this.sysObjects = sysObjects;
    }
    public SysRoles getSysRoles() {
        return this.sysRoles;
    }
    
    public void setSysRoles(SysRoles sysRoles) {
        this.sysRoles = sysRoles;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedTime() {
        return this.createdTime;
    }
    
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Date getUpdatedTime() {
        return this.updatedTime;
    }
    
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }
    public Integer getModificationNum() {
        return this.modificationNum;
    }
    
    public void setModificationNum(Integer modificationNum) {
        this.modificationNum = modificationNum;
    }
    public String getIsEnabled() {
        return this.isEnabled;
    }
    
    public void setIsEnabled(String isEnabled) {
        this.isEnabled = isEnabled;
    }
    public String getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }




}


