package model;
// Generated Aug 20, 2017 3:58:45 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SysUsers generated by hbm2java
 */
public class SysUsers  implements java.io.Serializable {


     private String userId;
     private SysPersons sysPersons;
     private String password;
     private String description;
     private String isPwdcanchanged;
     private Date lastPwdchanged;
     private Date lastLogin;
     private Date lastLogout;
     private String createdBy;
     private Date createdTime;
     private String updatedBy;
     private Date updatedTime;
     private Integer modificationNum;
     private String isEnabled;
     private String isDeleted;
     private Set sysUsersRoleses = new HashSet(0);

    public SysUsers() {
    }

	
    public SysUsers(String userId) {
        this.userId = userId;
    }
    public SysUsers(String userId, SysPersons sysPersons, String password, String description, String isPwdcanchanged, Date lastPwdchanged, Date lastLogin, Date lastLogout, String createdBy, Date createdTime, String updatedBy, Date updatedTime, Integer modificationNum, String isEnabled, String isDeleted, Set sysUsersRoleses) {
       this.userId = userId;
       this.sysPersons = sysPersons;
       this.password = password;
       this.description = description;
       this.isPwdcanchanged = isPwdcanchanged;
       this.lastPwdchanged = lastPwdchanged;
       this.lastLogin = lastLogin;
       this.lastLogout = lastLogout;
       this.createdBy = createdBy;
       this.createdTime = createdTime;
       this.updatedBy = updatedBy;
       this.updatedTime = updatedTime;
       this.modificationNum = modificationNum;
       this.isEnabled = isEnabled;
       this.isDeleted = isDeleted;
       this.sysUsersRoleses = sysUsersRoleses;
    }
   
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public SysPersons getSysPersons() {
        return this.sysPersons;
    }
    
    public void setSysPersons(SysPersons sysPersons) {
        this.sysPersons = sysPersons;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getIsPwdcanchanged() {
        return this.isPwdcanchanged;
    }
    
    public void setIsPwdcanchanged(String isPwdcanchanged) {
        this.isPwdcanchanged = isPwdcanchanged;
    }
    public Date getLastPwdchanged() {
        return this.lastPwdchanged;
    }
    
    public void setLastPwdchanged(Date lastPwdchanged) {
        this.lastPwdchanged = lastPwdchanged;
    }
    public Date getLastLogin() {
        return this.lastLogin;
    }
    
    public void setLastLogin(Date lastLogin) {
        this.lastLogin = lastLogin;
    }
    public Date getLastLogout() {
        return this.lastLogout;
    }
    
    public void setLastLogout(Date lastLogout) {
        this.lastLogout = lastLogout;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedTime() {
        return this.createdTime;
    }
    
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Date getUpdatedTime() {
        return this.updatedTime;
    }
    
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }
    public Integer getModificationNum() {
        return this.modificationNum;
    }
    
    public void setModificationNum(Integer modificationNum) {
        this.modificationNum = modificationNum;
    }
    public String getIsEnabled() {
        return this.isEnabled;
    }
    
    public void setIsEnabled(String isEnabled) {
        this.isEnabled = isEnabled;
    }
    public String getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }
    public Set getSysUsersRoleses() {
        return this.sysUsersRoleses;
    }
    
    public void setSysUsersRoleses(Set sysUsersRoleses) {
        this.sysUsersRoleses = sysUsersRoleses;
    }




}


