package model;
// Generated Aug 20, 2017 3:58:45 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TrxBillings generated by hbm2java
 */
public class TrxBillings  implements java.io.Serializable {


     private String billingId;
     private MstCustomers mstCustomers;
     private String billingStatus;
     private Date periodStart;
     private Date periodEnd;
     private String custLegalName;
     private int invoicedStoreTotal;
     private int invoicedRitaseTotal;
     private int invoicedDistanceTotal;
     private int invoicedAmountTotal;
     private String createdBy;
     private Date createdTime;
     private String updatedBy;
     private Date updatedTime;
     private Integer modificationNum;
     private String isEnabled;
     private String isDeleted;
     private Set trxDeliveryRequestses = new HashSet(0);

    public TrxBillings() {
    }

	
    public TrxBillings(String billingId, int invoicedStoreTotal, int invoicedRitaseTotal, int invoicedDistanceTotal, int invoicedAmountTotal) {
        this.billingId = billingId;
        this.invoicedStoreTotal = invoicedStoreTotal;
        this.invoicedRitaseTotal = invoicedRitaseTotal;
        this.invoicedDistanceTotal = invoicedDistanceTotal;
        this.invoicedAmountTotal = invoicedAmountTotal;
    }
    public TrxBillings(String billingId, MstCustomers mstCustomers, String billingStatus, Date periodStart, Date periodEnd, String custLegalName, int invoicedStoreTotal, int invoicedRitaseTotal, int invoicedDistanceTotal, int invoicedAmountTotal, String createdBy, Date createdTime, String updatedBy, Date updatedTime, Integer modificationNum, String isEnabled, String isDeleted, Set trxDeliveryRequestses) {
       this.billingId = billingId;
       this.mstCustomers = mstCustomers;
       this.billingStatus = billingStatus;
       this.periodStart = periodStart;
       this.periodEnd = periodEnd;
       this.custLegalName = custLegalName;
       this.invoicedStoreTotal = invoicedStoreTotal;
       this.invoicedRitaseTotal = invoicedRitaseTotal;
       this.invoicedDistanceTotal = invoicedDistanceTotal;
       this.invoicedAmountTotal = invoicedAmountTotal;
       this.createdBy = createdBy;
       this.createdTime = createdTime;
       this.updatedBy = updatedBy;
       this.updatedTime = updatedTime;
       this.modificationNum = modificationNum;
       this.isEnabled = isEnabled;
       this.isDeleted = isDeleted;
       this.trxDeliveryRequestses = trxDeliveryRequestses;
    }
   
    public String getBillingId() {
        return this.billingId;
    }
    
    public void setBillingId(String billingId) {
        this.billingId = billingId;
    }
    public MstCustomers getMstCustomers() {
        return this.mstCustomers;
    }
    
    public void setMstCustomers(MstCustomers mstCustomers) {
        this.mstCustomers = mstCustomers;
    }
    public String getBillingStatus() {
        return this.billingStatus;
    }
    
    public void setBillingStatus(String billingStatus) {
        this.billingStatus = billingStatus;
    }
    public Date getPeriodStart() {
        return this.periodStart;
    }
    
    public void setPeriodStart(Date periodStart) {
        this.periodStart = periodStart;
    }
    public Date getPeriodEnd() {
        return this.periodEnd;
    }
    
    public void setPeriodEnd(Date periodEnd) {
        this.periodEnd = periodEnd;
    }
    public String getCustLegalName() {
        return this.custLegalName;
    }
    
    public void setCustLegalName(String custLegalName) {
        this.custLegalName = custLegalName;
    }
    public int getInvoicedStoreTotal() {
        return this.invoicedStoreTotal;
    }
    
    public void setInvoicedStoreTotal(int invoicedStoreTotal) {
        this.invoicedStoreTotal = invoicedStoreTotal;
    }
    public int getInvoicedRitaseTotal() {
        return this.invoicedRitaseTotal;
    }
    
    public void setInvoicedRitaseTotal(int invoicedRitaseTotal) {
        this.invoicedRitaseTotal = invoicedRitaseTotal;
    }
    public int getInvoicedDistanceTotal() {
        return this.invoicedDistanceTotal;
    }
    
    public void setInvoicedDistanceTotal(int invoicedDistanceTotal) {
        this.invoicedDistanceTotal = invoicedDistanceTotal;
    }
    public int getInvoicedAmountTotal() {
        return this.invoicedAmountTotal;
    }
    
    public void setInvoicedAmountTotal(int invoicedAmountTotal) {
        this.invoicedAmountTotal = invoicedAmountTotal;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedTime() {
        return this.createdTime;
    }
    
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Date getUpdatedTime() {
        return this.updatedTime;
    }
    
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }
    public Integer getModificationNum() {
        return this.modificationNum;
    }
    
    public void setModificationNum(Integer modificationNum) {
        this.modificationNum = modificationNum;
    }
    public String getIsEnabled() {
        return this.isEnabled;
    }
    
    public void setIsEnabled(String isEnabled) {
        this.isEnabled = isEnabled;
    }
    public String getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }
    public Set getTrxDeliveryRequestses() {
        return this.trxDeliveryRequestses;
    }
    
    public void setTrxDeliveryRequestses(Set trxDeliveryRequestses) {
        this.trxDeliveryRequestses = trxDeliveryRequestses;
    }




}


