package model;
// Generated Aug 20, 2017 3:58:45 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TrxDriverAvailibilty generated by hbm2java
 */
public class TrxDriverAvailibilty  implements java.io.Serializable {


     private Integer rowId;
     private MstDrivers mstDrivers;
     private Date touchTime;

    public TrxDriverAvailibilty() {
    }

	
    public TrxDriverAvailibilty(MstDrivers mstDrivers) {
        this.mstDrivers = mstDrivers;
    }
    public TrxDriverAvailibilty(MstDrivers mstDrivers, Date touchTime) {
       this.mstDrivers = mstDrivers;
       this.touchTime = touchTime;
    }
   
    public Integer getRowId() {
        return this.rowId;
    }
    
    public void setRowId(Integer rowId) {
        this.rowId = rowId;
    }
    public MstDrivers getMstDrivers() {
        return this.mstDrivers;
    }
    
    public void setMstDrivers(MstDrivers mstDrivers) {
        this.mstDrivers = mstDrivers;
    }
    public Date getTouchTime() {
        return this.touchTime;
    }
    
    public void setTouchTime(Date touchTime) {
        this.touchTime = touchTime;
    }




}


