package model;
// Generated Aug 20, 2017 3:58:45 PM by Hibernate Tools 4.3.1



/**
 * TrxDeliveryRequestsPodsId generated by hbm2java
 */
public class TrxDeliveryRequestsPodsId  implements java.io.Serializable {


     private String dreqNum;
     private String toPodId;

    public TrxDeliveryRequestsPodsId() {
    }

    public TrxDeliveryRequestsPodsId(String dreqNum, String toPodId) {
       this.dreqNum = dreqNum;
       this.toPodId = toPodId;
    }
   
    public String getDreqNum() {
        return this.dreqNum;
    }
    
    public void setDreqNum(String dreqNum) {
        this.dreqNum = dreqNum;
    }
    public String getToPodId() {
        return this.toPodId;
    }
    
    public void setToPodId(String toPodId) {
        this.toPodId = toPodId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TrxDeliveryRequestsPodsId) ) return false;
		 TrxDeliveryRequestsPodsId castOther = ( TrxDeliveryRequestsPodsId ) other; 
         
		 return ( (this.getDreqNum()==castOther.getDreqNum()) || ( this.getDreqNum()!=null && castOther.getDreqNum()!=null && this.getDreqNum().equals(castOther.getDreqNum()) ) )
 && ( (this.getToPodId()==castOther.getToPodId()) || ( this.getToPodId()!=null && castOther.getToPodId()!=null && this.getToPodId().equals(castOther.getToPodId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getDreqNum() == null ? 0 : this.getDreqNum().hashCode() );
         result = 37 * result + ( getToPodId() == null ? 0 : this.getToPodId().hashCode() );
         return result;
   }   


}


