package model;
// Generated Aug 20, 2017 3:58:45 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TrxDeliveryRequestsExpenses generated by hbm2java
 */
public class TrxDeliveryRequestsExpenses  implements java.io.Serializable {


     private TrxDeliveryRequestsExpensesId id;
     private TrxDeliveryRequests trxDeliveryRequests;
     private int advanceAmount;
     private int actualAmount;
     private String createdBy;
     private Date createdTime;
     private String updatedBy;
     private Date updatedTime;
     private Integer modificationNum;
     private String isEnabled;
     private String isDeleted;

    public TrxDeliveryRequestsExpenses() {
    }

	
    public TrxDeliveryRequestsExpenses(TrxDeliveryRequestsExpensesId id, TrxDeliveryRequests trxDeliveryRequests, int advanceAmount, int actualAmount) {
        this.id = id;
        this.trxDeliveryRequests = trxDeliveryRequests;
        this.advanceAmount = advanceAmount;
        this.actualAmount = actualAmount;
    }
    public TrxDeliveryRequestsExpenses(TrxDeliveryRequestsExpensesId id, TrxDeliveryRequests trxDeliveryRequests, int advanceAmount, int actualAmount, String createdBy, Date createdTime, String updatedBy, Date updatedTime, Integer modificationNum, String isEnabled, String isDeleted) {
       this.id = id;
       this.trxDeliveryRequests = trxDeliveryRequests;
       this.advanceAmount = advanceAmount;
       this.actualAmount = actualAmount;
       this.createdBy = createdBy;
       this.createdTime = createdTime;
       this.updatedBy = updatedBy;
       this.updatedTime = updatedTime;
       this.modificationNum = modificationNum;
       this.isEnabled = isEnabled;
       this.isDeleted = isDeleted;
    }
   
    public TrxDeliveryRequestsExpensesId getId() {
        return this.id;
    }
    
    public void setId(TrxDeliveryRequestsExpensesId id) {
        this.id = id;
    }
    public TrxDeliveryRequests getTrxDeliveryRequests() {
        return this.trxDeliveryRequests;
    }
    
    public void setTrxDeliveryRequests(TrxDeliveryRequests trxDeliveryRequests) {
        this.trxDeliveryRequests = trxDeliveryRequests;
    }
    public int getAdvanceAmount() {
        return this.advanceAmount;
    }
    
    public void setAdvanceAmount(int advanceAmount) {
        this.advanceAmount = advanceAmount;
    }
    public int getActualAmount() {
        return this.actualAmount;
    }
    
    public void setActualAmount(int actualAmount) {
        this.actualAmount = actualAmount;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedTime() {
        return this.createdTime;
    }
    
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Date getUpdatedTime() {
        return this.updatedTime;
    }
    
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }
    public Integer getModificationNum() {
        return this.modificationNum;
    }
    
    public void setModificationNum(Integer modificationNum) {
        this.modificationNum = modificationNum;
    }
    public String getIsEnabled() {
        return this.isEnabled;
    }
    
    public void setIsEnabled(String isEnabled) {
        this.isEnabled = isEnabled;
    }
    public String getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }




}


