package model;
// Generated Aug 20, 2017 3:58:45 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TrxDeliveryRequestsPods generated by hbm2java
 */
public class TrxDeliveryRequestsPods  implements java.io.Serializable {


     private TrxDeliveryRequestsPodsId id;
     private MstDropPoints mstDropPoints;
     private TrxDeliveryRequests trxDeliveryRequests;
     private int podSeq;
     private String fromPodId;
     private String fromPodShortname;
     private String fromPodFullname;
     private String toPodShortname;
     private String toPodFullname;
     private int onpackageP2pdistance;
     private int actualP2pdistance;
     private String is24hrsOpened;
     private Date checkinTime;
     private Date checkoutTime;
     private int checkinOdoValue;
     private byte[] checkinOdoPict;
     private int cargoValueAmount;
     private String receivedBy;
     private byte[] receiverSignature;
     private String note;

    public TrxDeliveryRequestsPods() {
    }

	
    public TrxDeliveryRequestsPods(TrxDeliveryRequestsPodsId id, MstDropPoints mstDropPoints, TrxDeliveryRequests trxDeliveryRequests, int podSeq, String fromPodId, int onpackageP2pdistance, int actualP2pdistance, int checkinOdoValue, int cargoValueAmount) {
        this.id = id;
        this.mstDropPoints = mstDropPoints;
        this.trxDeliveryRequests = trxDeliveryRequests;
        this.podSeq = podSeq;
        this.fromPodId = fromPodId;
        this.onpackageP2pdistance = onpackageP2pdistance;
        this.actualP2pdistance = actualP2pdistance;
        this.checkinOdoValue = checkinOdoValue;
        this.cargoValueAmount = cargoValueAmount;
    }
    public TrxDeliveryRequestsPods(TrxDeliveryRequestsPodsId id, MstDropPoints mstDropPoints, TrxDeliveryRequests trxDeliveryRequests, int podSeq, String fromPodId, String fromPodShortname, String fromPodFullname, String toPodShortname, String toPodFullname, int onpackageP2pdistance, int actualP2pdistance, String is24hrsOpened, Date checkinTime, Date checkoutTime, int checkinOdoValue, byte[] checkinOdoPict, int cargoValueAmount, String receivedBy, byte[] receiverSignature, String note) {
       this.id = id;
       this.mstDropPoints = mstDropPoints;
       this.trxDeliveryRequests = trxDeliveryRequests;
       this.podSeq = podSeq;
       this.fromPodId = fromPodId;
       this.fromPodShortname = fromPodShortname;
       this.fromPodFullname = fromPodFullname;
       this.toPodShortname = toPodShortname;
       this.toPodFullname = toPodFullname;
       this.onpackageP2pdistance = onpackageP2pdistance;
       this.actualP2pdistance = actualP2pdistance;
       this.is24hrsOpened = is24hrsOpened;
       this.checkinTime = checkinTime;
       this.checkoutTime = checkoutTime;
       this.checkinOdoValue = checkinOdoValue;
       this.checkinOdoPict = checkinOdoPict;
       this.cargoValueAmount = cargoValueAmount;
       this.receivedBy = receivedBy;
       this.receiverSignature = receiverSignature;
       this.note = note;
    }
   
    public TrxDeliveryRequestsPodsId getId() {
        return this.id;
    }
    
    public void setId(TrxDeliveryRequestsPodsId id) {
        this.id = id;
    }
    public MstDropPoints getMstDropPoints() {
        return this.mstDropPoints;
    }
    
    public void setMstDropPoints(MstDropPoints mstDropPoints) {
        this.mstDropPoints = mstDropPoints;
    }
    public TrxDeliveryRequests getTrxDeliveryRequests() {
        return this.trxDeliveryRequests;
    }
    
    public void setTrxDeliveryRequests(TrxDeliveryRequests trxDeliveryRequests) {
        this.trxDeliveryRequests = trxDeliveryRequests;
    }
    public int getPodSeq() {
        return this.podSeq;
    }
    
    public void setPodSeq(int podSeq) {
        this.podSeq = podSeq;
    }
    public String getFromPodId() {
        return this.fromPodId;
    }
    
    public void setFromPodId(String fromPodId) {
        this.fromPodId = fromPodId;
    }
    public String getFromPodShortname() {
        return this.fromPodShortname;
    }
    
    public void setFromPodShortname(String fromPodShortname) {
        this.fromPodShortname = fromPodShortname;
    }
    public String getFromPodFullname() {
        return this.fromPodFullname;
    }
    
    public void setFromPodFullname(String fromPodFullname) {
        this.fromPodFullname = fromPodFullname;
    }
    public String getToPodShortname() {
        return this.toPodShortname;
    }
    
    public void setToPodShortname(String toPodShortname) {
        this.toPodShortname = toPodShortname;
    }
    public String getToPodFullname() {
        return this.toPodFullname;
    }
    
    public void setToPodFullname(String toPodFullname) {
        this.toPodFullname = toPodFullname;
    }
    public int getOnpackageP2pdistance() {
        return this.onpackageP2pdistance;
    }
    
    public void setOnpackageP2pdistance(int onpackageP2pdistance) {
        this.onpackageP2pdistance = onpackageP2pdistance;
    }
    public int getActualP2pdistance() {
        return this.actualP2pdistance;
    }
    
    public void setActualP2pdistance(int actualP2pdistance) {
        this.actualP2pdistance = actualP2pdistance;
    }
    public String getIs24hrsOpened() {
        return this.is24hrsOpened;
    }
    
    public void setIs24hrsOpened(String is24hrsOpened) {
        this.is24hrsOpened = is24hrsOpened;
    }
    public Date getCheckinTime() {
        return this.checkinTime;
    }
    
    public void setCheckinTime(Date checkinTime) {
        this.checkinTime = checkinTime;
    }
    public Date getCheckoutTime() {
        return this.checkoutTime;
    }
    
    public void setCheckoutTime(Date checkoutTime) {
        this.checkoutTime = checkoutTime;
    }
    public int getCheckinOdoValue() {
        return this.checkinOdoValue;
    }
    
    public void setCheckinOdoValue(int checkinOdoValue) {
        this.checkinOdoValue = checkinOdoValue;
    }
    public byte[] getCheckinOdoPict() {
        return this.checkinOdoPict;
    }
    
    public void setCheckinOdoPict(byte[] checkinOdoPict) {
        this.checkinOdoPict = checkinOdoPict;
    }
    public int getCargoValueAmount() {
        return this.cargoValueAmount;
    }
    
    public void setCargoValueAmount(int cargoValueAmount) {
        this.cargoValueAmount = cargoValueAmount;
    }
    public String getReceivedBy() {
        return this.receivedBy;
    }
    
    public void setReceivedBy(String receivedBy) {
        this.receivedBy = receivedBy;
    }
    public byte[] getReceiverSignature() {
        return this.receiverSignature;
    }
    
    public void setReceiverSignature(byte[] receiverSignature) {
        this.receiverSignature = receiverSignature;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }




}


