package model;
// Generated Aug 20, 2017 3:58:45 PM by Hibernate Tools 4.3.1



/**
 * TrxDeliveryRequestsExpensesId generated by hbm2java
 */
public class TrxDeliveryRequestsExpensesId  implements java.io.Serializable {


     private String dreqNum;
     private String expenseName;

    public TrxDeliveryRequestsExpensesId() {
    }

    public TrxDeliveryRequestsExpensesId(String dreqNum, String expenseName) {
       this.dreqNum = dreqNum;
       this.expenseName = expenseName;
    }
   
    public String getDreqNum() {
        return this.dreqNum;
    }
    
    public void setDreqNum(String dreqNum) {
        this.dreqNum = dreqNum;
    }
    public String getExpenseName() {
        return this.expenseName;
    }
    
    public void setExpenseName(String expenseName) {
        this.expenseName = expenseName;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TrxDeliveryRequestsExpensesId) ) return false;
		 TrxDeliveryRequestsExpensesId castOther = ( TrxDeliveryRequestsExpensesId ) other; 
         
		 return ( (this.getDreqNum()==castOther.getDreqNum()) || ( this.getDreqNum()!=null && castOther.getDreqNum()!=null && this.getDreqNum().equals(castOther.getDreqNum()) ) )
 && ( (this.getExpenseName()==castOther.getExpenseName()) || ( this.getExpenseName()!=null && castOther.getExpenseName()!=null && this.getExpenseName().equals(castOther.getExpenseName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getDreqNum() == null ? 0 : this.getDreqNum().hashCode() );
         result = 37 * result + ( getExpenseName() == null ? 0 : this.getExpenseName().hashCode() );
         return result;
   }   


}


