package model;
// Generated Aug 20, 2017 3:58:45 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TrxDeliveryRequests generated by hbm2java
 */
public class TrxDeliveryRequests  implements java.io.Serializable {


     private String dreqNum;
     private MstCustomers mstCustomers;
     private MstDrivers mstDrivers;
     private MstFleet mstFleet;
     private TrxBillings trxBillings;
     private Date plannedDreqDate;
     private Date actualDreqDate;
     private String dreqStatus;
     private String cargoType;
     private String custLegalName;
     private String custAddress;
     private String custAddress2;
     private String custCity;
     private String custProvince;
     private String custCountry;
     private String driverName;
     private Integer ritaseSeq;
     private String plateNum;
     private Date actualDepTime;
     private Date actualArrTime;
     private int actualOdoStart;
     private int actualOdoEnd;
     private int actualDistanceTotal;
     private int onpackageDistanceTotal;
     private int billedDistanceTotal;
     private int billedAmountTotal;
     private int advanceExpTotal;
     private int actualExpTotal;
     private int remainingExpAmount;
     private int borrowedAmount;
     private int cargoValueTotal;
     private String note;
     private byte[] odoStartPict;
     private byte[] odoEndPict;
     private Date toplannedDate;
     private Date topreparedDate;
     private Date toondeliveryDate;
     private Date toincompleteDate;
     private Date tocompleteDate;
     private Date tobillassignedDate;
     private Date topaidDate;
     private Date tocancelledDate;
     private String createdBy;
     private Date createdTime;
     private String updatedBy;
     private Date updatedTime;
     private Integer modificationNum;
     private String isEnabled;
     private String isDeleted;
     private Set trxDeliveryRequestsPodses = new HashSet(0);
     private Set trxDeliveryRequestsExpenseses = new HashSet(0);

    public TrxDeliveryRequests() {
    }

	
    public TrxDeliveryRequests(String dreqNum, int actualOdoStart, int actualOdoEnd, int actualDistanceTotal, int onpackageDistanceTotal, int billedDistanceTotal, int billedAmountTotal, int advanceExpTotal, int actualExpTotal, int remainingExpAmount, int borrowedAmount, int cargoValueTotal) {
        this.dreqNum = dreqNum;
        this.actualOdoStart = actualOdoStart;
        this.actualOdoEnd = actualOdoEnd;
        this.actualDistanceTotal = actualDistanceTotal;
        this.onpackageDistanceTotal = onpackageDistanceTotal;
        this.billedDistanceTotal = billedDistanceTotal;
        this.billedAmountTotal = billedAmountTotal;
        this.advanceExpTotal = advanceExpTotal;
        this.actualExpTotal = actualExpTotal;
        this.remainingExpAmount = remainingExpAmount;
        this.borrowedAmount = borrowedAmount;
        this.cargoValueTotal = cargoValueTotal;
    }
    public TrxDeliveryRequests(String dreqNum, MstCustomers mstCustomers, MstDrivers mstDrivers, MstFleet mstFleet, TrxBillings trxBillings, Date plannedDreqDate, Date actualDreqDate, String dreqStatus, String cargoType, String custLegalName, String custAddress, String custAddress2, String custCity, String custProvince, String custCountry, String driverName, Integer ritaseSeq, String plateNum, Date actualDepTime, Date actualArrTime, int actualOdoStart, int actualOdoEnd, int actualDistanceTotal, int onpackageDistanceTotal, int billedDistanceTotal, int billedAmountTotal, int advanceExpTotal, int actualExpTotal, int remainingExpAmount, int borrowedAmount, int cargoValueTotal, String note, byte[] odoStartPict, byte[] odoEndPict, Date toplannedDate, Date topreparedDate, Date toondeliveryDate, Date toincompleteDate, Date tocompleteDate, Date tobillassignedDate, Date topaidDate, Date tocancelledDate, String createdBy, Date createdTime, String updatedBy, Date updatedTime, Integer modificationNum, String isEnabled, String isDeleted, Set trxDeliveryRequestsPodses, Set trxDeliveryRequestsExpenseses) {
       this.dreqNum = dreqNum;
       this.mstCustomers = mstCustomers;
       this.mstDrivers = mstDrivers;
       this.mstFleet = mstFleet;
       this.trxBillings = trxBillings;
       this.plannedDreqDate = plannedDreqDate;
       this.actualDreqDate = actualDreqDate;
       this.dreqStatus = dreqStatus;
       this.cargoType = cargoType;
       this.custLegalName = custLegalName;
       this.custAddress = custAddress;
       this.custAddress2 = custAddress2;
       this.custCity = custCity;
       this.custProvince = custProvince;
       this.custCountry = custCountry;
       this.driverName = driverName;
       this.ritaseSeq = ritaseSeq;
       this.plateNum = plateNum;
       this.actualDepTime = actualDepTime;
       this.actualArrTime = actualArrTime;
       this.actualOdoStart = actualOdoStart;
       this.actualOdoEnd = actualOdoEnd;
       this.actualDistanceTotal = actualDistanceTotal;
       this.onpackageDistanceTotal = onpackageDistanceTotal;
       this.billedDistanceTotal = billedDistanceTotal;
       this.billedAmountTotal = billedAmountTotal;
       this.advanceExpTotal = advanceExpTotal;
       this.actualExpTotal = actualExpTotal;
       this.remainingExpAmount = remainingExpAmount;
       this.borrowedAmount = borrowedAmount;
       this.cargoValueTotal = cargoValueTotal;
       this.note = note;
       this.odoStartPict = odoStartPict;
       this.odoEndPict = odoEndPict;
       this.toplannedDate = toplannedDate;
       this.topreparedDate = topreparedDate;
       this.toondeliveryDate = toondeliveryDate;
       this.toincompleteDate = toincompleteDate;
       this.tocompleteDate = tocompleteDate;
       this.tobillassignedDate = tobillassignedDate;
       this.topaidDate = topaidDate;
       this.tocancelledDate = tocancelledDate;
       this.createdBy = createdBy;
       this.createdTime = createdTime;
       this.updatedBy = updatedBy;
       this.updatedTime = updatedTime;
       this.modificationNum = modificationNum;
       this.isEnabled = isEnabled;
       this.isDeleted = isDeleted;
       this.trxDeliveryRequestsPodses = trxDeliveryRequestsPodses;
       this.trxDeliveryRequestsExpenseses = trxDeliveryRequestsExpenseses;
    }
   
    public String getDreqNum() {
        return this.dreqNum;
    }
    
    public void setDreqNum(String dreqNum) {
        this.dreqNum = dreqNum;
    }
    public MstCustomers getMstCustomers() {
        return this.mstCustomers;
    }
    
    public void setMstCustomers(MstCustomers mstCustomers) {
        this.mstCustomers = mstCustomers;
    }
    public MstDrivers getMstDrivers() {
        return this.mstDrivers;
    }
    
    public void setMstDrivers(MstDrivers mstDrivers) {
        this.mstDrivers = mstDrivers;
    }
    public MstFleet getMstFleet() {
        return this.mstFleet;
    }
    
    public void setMstFleet(MstFleet mstFleet) {
        this.mstFleet = mstFleet;
    }
    public TrxBillings getTrxBillings() {
        return this.trxBillings;
    }
    
    public void setTrxBillings(TrxBillings trxBillings) {
        this.trxBillings = trxBillings;
    }
    public Date getPlannedDreqDate() {
        return this.plannedDreqDate;
    }
    
    public void setPlannedDreqDate(Date plannedDreqDate) {
        this.plannedDreqDate = plannedDreqDate;
    }
    public Date getActualDreqDate() {
        return this.actualDreqDate;
    }
    
    public void setActualDreqDate(Date actualDreqDate) {
        this.actualDreqDate = actualDreqDate;
    }
    public String getDreqStatus() {
        return this.dreqStatus;
    }
    
    public void setDreqStatus(String dreqStatus) {
        this.dreqStatus = dreqStatus;
    }
    public String getCargoType() {
        return this.cargoType;
    }
    
    public void setCargoType(String cargoType) {
        this.cargoType = cargoType;
    }
    public String getCustLegalName() {
        return this.custLegalName;
    }
    
    public void setCustLegalName(String custLegalName) {
        this.custLegalName = custLegalName;
    }
    public String getCustAddress() {
        return this.custAddress;
    }
    
    public void setCustAddress(String custAddress) {
        this.custAddress = custAddress;
    }
    public String getCustAddress2() {
        return this.custAddress2;
    }
    
    public void setCustAddress2(String custAddress2) {
        this.custAddress2 = custAddress2;
    }
    public String getCustCity() {
        return this.custCity;
    }
    
    public void setCustCity(String custCity) {
        this.custCity = custCity;
    }
    public String getCustProvince() {
        return this.custProvince;
    }
    
    public void setCustProvince(String custProvince) {
        this.custProvince = custProvince;
    }
    public String getCustCountry() {
        return this.custCountry;
    }
    
    public void setCustCountry(String custCountry) {
        this.custCountry = custCountry;
    }
    public String getDriverName() {
        return this.driverName;
    }
    
    public void setDriverName(String driverName) {
        this.driverName = driverName;
    }
    public Integer getRitaseSeq() {
        return this.ritaseSeq;
    }
    
    public void setRitaseSeq(Integer ritaseSeq) {
        this.ritaseSeq = ritaseSeq;
    }
    public String getPlateNum() {
        return this.plateNum;
    }
    
    public void setPlateNum(String plateNum) {
        this.plateNum = plateNum;
    }
    public Date getActualDepTime() {
        return this.actualDepTime;
    }
    
    public void setActualDepTime(Date actualDepTime) {
        this.actualDepTime = actualDepTime;
    }
    public Date getActualArrTime() {
        return this.actualArrTime;
    }
    
    public void setActualArrTime(Date actualArrTime) {
        this.actualArrTime = actualArrTime;
    }
    public int getActualOdoStart() {
        return this.actualOdoStart;
    }
    
    public void setActualOdoStart(int actualOdoStart) {
        this.actualOdoStart = actualOdoStart;
    }
    public int getActualOdoEnd() {
        return this.actualOdoEnd;
    }
    
    public void setActualOdoEnd(int actualOdoEnd) {
        this.actualOdoEnd = actualOdoEnd;
    }
    public int getActualDistanceTotal() {
        return this.actualDistanceTotal;
    }
    
    public void setActualDistanceTotal(int actualDistanceTotal) {
        this.actualDistanceTotal = actualDistanceTotal;
    }
    public int getOnpackageDistanceTotal() {
        return this.onpackageDistanceTotal;
    }
    
    public void setOnpackageDistanceTotal(int onpackageDistanceTotal) {
        this.onpackageDistanceTotal = onpackageDistanceTotal;
    }
    public int getBilledDistanceTotal() {
        return this.billedDistanceTotal;
    }
    
    public void setBilledDistanceTotal(int billedDistanceTotal) {
        this.billedDistanceTotal = billedDistanceTotal;
    }
    public int getBilledAmountTotal() {
        return this.billedAmountTotal;
    }
    
    public void setBilledAmountTotal(int billedAmountTotal) {
        this.billedAmountTotal = billedAmountTotal;
    }
    public int getAdvanceExpTotal() {
        return this.advanceExpTotal;
    }
    
    public void setAdvanceExpTotal(int advanceExpTotal) {
        this.advanceExpTotal = advanceExpTotal;
    }
    public int getActualExpTotal() {
        return this.actualExpTotal;
    }
    
    public void setActualExpTotal(int actualExpTotal) {
        this.actualExpTotal = actualExpTotal;
    }
    public int getRemainingExpAmount() {
        return this.remainingExpAmount;
    }
    
    public void setRemainingExpAmount(int remainingExpAmount) {
        this.remainingExpAmount = remainingExpAmount;
    }
    public int getBorrowedAmount() {
        return this.borrowedAmount;
    }
    
    public void setBorrowedAmount(int borrowedAmount) {
        this.borrowedAmount = borrowedAmount;
    }
    public int getCargoValueTotal() {
        return this.cargoValueTotal;
    }
    
    public void setCargoValueTotal(int cargoValueTotal) {
        this.cargoValueTotal = cargoValueTotal;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public byte[] getOdoStartPict() {
        return this.odoStartPict;
    }
    
    public void setOdoStartPict(byte[] odoStartPict) {
        this.odoStartPict = odoStartPict;
    }
    public byte[] getOdoEndPict() {
        return this.odoEndPict;
    }
    
    public void setOdoEndPict(byte[] odoEndPict) {
        this.odoEndPict = odoEndPict;
    }
    public Date getToplannedDate() {
        return this.toplannedDate;
    }
    
    public void setToplannedDate(Date toplannedDate) {
        this.toplannedDate = toplannedDate;
    }
    public Date getTopreparedDate() {
        return this.topreparedDate;
    }
    
    public void setTopreparedDate(Date topreparedDate) {
        this.topreparedDate = topreparedDate;
    }
    public Date getToondeliveryDate() {
        return this.toondeliveryDate;
    }
    
    public void setToondeliveryDate(Date toondeliveryDate) {
        this.toondeliveryDate = toondeliveryDate;
    }
    public Date getToincompleteDate() {
        return this.toincompleteDate;
    }
    
    public void setToincompleteDate(Date toincompleteDate) {
        this.toincompleteDate = toincompleteDate;
    }
    public Date getTocompleteDate() {
        return this.tocompleteDate;
    }
    
    public void setTocompleteDate(Date tocompleteDate) {
        this.tocompleteDate = tocompleteDate;
    }
    public Date getTobillassignedDate() {
        return this.tobillassignedDate;
    }
    
    public void setTobillassignedDate(Date tobillassignedDate) {
        this.tobillassignedDate = tobillassignedDate;
    }
    public Date getTopaidDate() {
        return this.topaidDate;
    }
    
    public void setTopaidDate(Date topaidDate) {
        this.topaidDate = topaidDate;
    }
    public Date getTocancelledDate() {
        return this.tocancelledDate;
    }
    
    public void setTocancelledDate(Date tocancelledDate) {
        this.tocancelledDate = tocancelledDate;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedTime() {
        return this.createdTime;
    }
    
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Date getUpdatedTime() {
        return this.updatedTime;
    }
    
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }
    public Integer getModificationNum() {
        return this.modificationNum;
    }
    
    public void setModificationNum(Integer modificationNum) {
        this.modificationNum = modificationNum;
    }
    public String getIsEnabled() {
        return this.isEnabled;
    }
    
    public void setIsEnabled(String isEnabled) {
        this.isEnabled = isEnabled;
    }
    public String getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }
    public Set getTrxDeliveryRequestsPodses() {
        return this.trxDeliveryRequestsPodses;
    }
    
    public void setTrxDeliveryRequestsPodses(Set trxDeliveryRequestsPodses) {
        this.trxDeliveryRequestsPodses = trxDeliveryRequestsPodses;
    }
    public Set getTrxDeliveryRequestsExpenseses() {
        return this.trxDeliveryRequestsExpenseses;
    }
    
    public void setTrxDeliveryRequestsExpenseses(Set trxDeliveryRequestsExpenseses) {
        this.trxDeliveryRequestsExpenseses = trxDeliveryRequestsExpenseses;
    }




}


