package model;
// Generated Aug 2, 2017 11:44:35 PM by Hibernate Tools 4.3.1



/**
 * UserRolesObjectsId generated by hbm2java
 */
public class UserRolesObjectsId  implements java.io.Serializable {


     private String userName;
     private int roleId;
     private int objectId;

    public UserRolesObjectsId() {
    }

    public UserRolesObjectsId(String userName, int roleId, int objectId) {
       this.userName = userName;
       this.roleId = roleId;
       this.objectId = objectId;
    }
   
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public int getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(int roleId) {
        this.roleId = roleId;
    }
    public int getObjectId() {
        return this.objectId;
    }
    
    public void setObjectId(int objectId) {
        this.objectId = objectId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UserRolesObjectsId) ) return false;
		 UserRolesObjectsId castOther = ( UserRolesObjectsId ) other; 
         
		 return ( (this.getUserName()==castOther.getUserName()) || ( this.getUserName()!=null && castOther.getUserName()!=null && this.getUserName().equals(castOther.getUserName()) ) )
 && (this.getRoleId()==castOther.getRoleId())
 && (this.getObjectId()==castOther.getObjectId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUserName() == null ? 0 : this.getUserName().hashCode() );
         result = 37 * result + this.getRoleId();
         result = 37 * result + this.getObjectId();
         return result;
   }   


}


