package model;
// Generated Aug 2, 2017 11:44:35 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * UserRolesObjects generated by hbm2java
 */
public class UserRolesObjects  implements java.io.Serializable {


     private UserRolesObjectsId id;
     private Objects objects;
     private Roles roles;
     private Users users;
     private String createdBy;
     private Date createdDate;
     private String updatedBy;
     private Date updatedDate;
     private String enabled;
     private String isDeleted;

    public UserRolesObjects() {
    }

	
    public UserRolesObjects(UserRolesObjectsId id, Objects objects, Roles roles, Users users) {
        this.id = id;
        this.objects = objects;
        this.roles = roles;
        this.users = users;
    }
    public UserRolesObjects(UserRolesObjectsId id, Objects objects, Roles roles, Users users, String createdBy, Date createdDate, String updatedBy, Date updatedDate, String enabled, String isDeleted) {
       this.id = id;
       this.objects = objects;
       this.roles = roles;
       this.users = users;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.updatedBy = updatedBy;
       this.updatedDate = updatedDate;
       this.enabled = enabled;
       this.isDeleted = isDeleted;
    }
   
    public UserRolesObjectsId getId() {
        return this.id;
    }
    
    public void setId(UserRolesObjectsId id) {
        this.id = id;
    }
    public Objects getObjects() {
        return this.objects;
    }
    
    public void setObjects(Objects objects) {
        this.objects = objects;
    }
    public Roles getRoles() {
        return this.roles;
    }
    
    public void setRoles(Roles roles) {
        this.roles = roles;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    public String getEnabled() {
        return this.enabled;
    }
    
    public void setEnabled(String enabled) {
        this.enabled = enabled;
    }
    public String getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }




}


